apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-hub
  namespace: jupyter
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    targetRevision: v1.3.1
    chart: jupyterhub
    repoURL: https://jupyterhub.github.io/helm-chart/
    helm:
      releaseName: jupyterhub
      # parameters:
      #   - name: ingress.enabled
      #     value: "true"
      #   - name: 
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter