metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"