name: Packer

on:
  push:
    branches:
      - main
    paths:
      - "packer/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./packer

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        
      - name: Configure .oci
        run: |
          mkdir -p ~/.oci
          echo [DEFAULT] >> ~/.oci/config
          echo user="${{ secrets.OCI_USER }}" >> ~/.oci/config
          echo fingerprint="${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo key_file=~/.oci/oci_api_key.pem >> ~/.oci/config
          echo tenancy="${{ secrets.OCI_TENANCY }}" >> ~/.oci/config
          echo region="${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "${{ secrets.OCI_PRIVATE_KEY }}" >> ~/.oci/oci_api_key.pem

      - name: Init Packer
        run: packer init .

      - name: Build image
        run: packer build -var "oci_file=~/.oci/config" .

      - name: Publish manifest
        uses: actions/upload-artifact@v2
        with:
          name: manifest
          path: "*/manifest.json"