name: Packer

on:
  push:
    branches:
      - main
    paths:
      - "packer/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        
# - name: Install oci-cli
#   if: steps.cache-oci-cli.outputs.cache-hit != 'true'
#   run: |
#     wget https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
#     sudo bash install.sh --accept-all-defaults --exec-dir /usr/local/bin
#     mkdir -p ~/.oci
#     echo [DEFAULT] >> ~/.oci/config
#     echo user="${{ secrets.OCI_USER }}" >> ~/.oci/config
#     echo fingerprint="${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
#     echo key_file=~/.oci/oci_api_key.pem >> ~/.oci/config
#     echo tenancy="${{ secrets.OCI_TENANCY }}" >> ~/.oci/config
#     echo region="${{ secrets.OCI_REGION }}" >> ~/.oci/config
#     echo "${{ secrets.OCI_API_KEY }}" >> ~/.oci/oci_api_key.pem
#     oci setup repair-file-permissions --file ~/.oci/config
#     oci setup repair-file-permissions --file ~/.oci/oci_api_key.pem
