name: Build sample images

on:
  push:
    tags:
      - "*"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ["sql", "storage"]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: flexwie
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          context: ${{ env.GITHUB_WORKSPACE }}/azure/k8s/identity/${{ matrix.dir }}
          file: ${{ env.GITHUB_WORKSPACE }}/azure/k8s/identity/Dockerfile
          tags: ghcr.io/flexwie/${{ matrix.dir }}:${{ github.ref_name }}

